import type { DocTag } from "@/lib/records/tag-records";
import { DOC_TAGS } from "@/lib/records/tag-records";

export type ActorType =
  | "program"
  | "institution"
  | "company"
  | "individual"
  | "care-operator";

export type ActorLayer =
  | "clinical-psychiatry"
  | "ai-labs-alignment"
  | "trust-safety-platform-risk"
  | "policy-standards"
  | "adjacent-bridge"
  | "care-delivery";

export type ActorRecord = {
  id: string;
  name: string;
  type: ActorType;
  layer: ActorLayer;
  organization?: string;
  role?: string;
  leverage: string;
  sees: string;
  misses: string;
  opportunity?: string;
  href?: string;
  region?: string;
  tags?: readonly DocTag[];
};

export type ActorMap = Record<string, ActorRecord>;

export const AI_PSYCHOSIS_ACTORS: ActorMap = {
  epinet: {
    id: "epinet",
    name: "EPINET",
    type: "program",
    layer: "clinical-psychiatry",
    organization: "Early Psychosis Intervention Network",
    role: "Federated early psychosis clinical network",
    leverage: "Tracks real intake patterns across sites where emerging psychosis presents early.",
    sees: "Structured clinical encounters and longitudinal care trajectories.",
    misses: "Standardized AI-specific interaction mechanism labels.",
    opportunity: "Embed AI exposure fields into intake and follow-up templates.",
    href: "https://nationalepinet.org/",
    tags: [DOC_TAGS.clinical, DOC_TAGS.clinicalEvidence, DOC_TAGS.landscape],
  },
  nimh: {
    id: "nimh",
    name: "NIMH",
    type: "institution",
    layer: "clinical-psychiatry",
    organization: "National Institute of Mental Health",
    role: "Major funder of early psychosis and digital psychiatry research",
    leverage: "Can fund multicenter studies and define evidence priorities.",
    sees: "Program-level outcomes and research portfolio signals.",
    misses: "Cross-domain standards that tightly couple AI telemetry to psychiatric outcomes.",
    opportunity: "Sponsor translational programs linking model behavior and clinical endpoints.",
    href: "https://www.nimh.nih.gov/",
    tags: [DOC_TAGS.clinical, DOC_TAGS.policy, DOC_TAGS.research],
  },
  ontrackny: {
    id: "ontrackny",
    name: "OnTrackNY",
    type: "program",
    layer: "clinical-psychiatry",
    role: "Real-world coordinated specialty care pipeline",
    leverage: "Operational intake and treatment workflows where AI-linked narratives can be detected.",
    sees: "Day-to-day early psychosis care delivery and follow-up.",
    misses: "Shared schema for AI-specific trigger mapping in routine documentation.",
    opportunity: "Pilot practical screening prompts for AI-mediated delusion reinforcement.",
    href: "https://www.ontrackny.org/",
    region: "United States",
    tags: [DOC_TAGS.clinical, DOC_TAGS.execution, DOC_TAGS.earlySignals],
  },
  orygen: {
    id: "orygen",
    name: "Orygen",
    type: "institution",
    layer: "clinical-psychiatry",
    role: "Advanced youth mental health and early psychosis organization",
    leverage: "Strong integration of early psychosis work with digital mental health practice.",
    sees: "Clinical symptom trajectories and intervention outcomes.",
    misses: "Common standards for attributing AI-specific causal contribution.",
    opportunity: "Lead international guidance on digital phenomenology in psychosis intake.",
    href: "https://www.orygen.org.au/",
    region: "Australia",
    tags: [DOC_TAGS.clinical, DOC_TAGS.publicHealth, DOC_TAGS.research],
  },
  john_torous: {
    id: "john_torous",
    name: "John Torous",
    type: "individual",
    layer: "clinical-psychiatry",
    organization: "Harvard / Beth Israel Deaconess",
    role: "Digital psychiatry leader",
    leverage: "Bridges psychiatry practice with mobile and AI mental health evidence.",
    sees: "Clinical realities of technology-mediated mental health impact.",
    misses: "Large-scale labeled data specifically on LLM-linked psychosis trajectories.",
    opportunity: "Define practical mechanism vocabulary for frontline clinicians.",
    tags: [DOC_TAGS.clinical, DOC_TAGS.research, DOC_TAGS.framework],
  },
  patricia_arean: {
    id: "patricia_arean",
    name: "Patricia Arean",
    type: "individual",
    layer: "clinical-psychiatry",
    organization: "University of Washington",
    role: "Clinical trials and digital intervention researcher",
    leverage: "Can test intervention designs in rigorous trial structures.",
    sees: "Treatment response and implementation outcomes.",
    misses: "Standardized AI delusion-risk exposure measures.",
    opportunity: "Operationalize trial-ready risk and mitigation endpoints.",
    tags: [DOC_TAGS.clinicalEvidence, DOC_TAGS.research, DOC_TAGS.metrics],
  },
  philip_mcguire: {
    id: "philip_mcguire",
    name: "Philip McGuire",
    type: "individual",
    layer: "clinical-psychiatry",
    organization: "King's College London",
    role: "Psychosis risk modeling researcher",
    leverage: "Deep expertise in psychosis risk stratification and early detection.",
    sees: "Risk progression modeling and warning indicators.",
    misses: "AI-specific exposure variables that fit existing psychosis risk models.",
    opportunity: "Integrate AI interaction features into psychosis risk modeling.",
    tags: [DOC_TAGS.clinicalEvidence, DOC_TAGS.metrics, DOC_TAGS.earlySignals],
  },

  openai: {
    id: "openai",
    name: "OpenAI",
    type: "company",
    layer: "ai-labs-alignment",
    role: "Frontier model and alignment research lab",
    leverage: "Large-scale conversation data and post-training experimentation.",
    sees: "Behavior drift, refusals, and reinforcement behavior inside product telemetry.",
    misses: "Clinical ground truth and long-term psychiatric outcomes.",
    opportunity: "Partner on privacy-preserving outcome linkage studies.",
    href: "https://openai.com/",
    tags: [DOC_TAGS.aiLabs, DOC_TAGS.mechanisms, DOC_TAGS.vendorReported],
  },
  anthropic: {
    id: "anthropic",
    name: "Anthropic",
    type: "company",
    layer: "ai-labs-alignment",
    role: "AI safety-focused model lab",
    leverage: "Strong interpretability and safety eval culture.",
    sees: "Alignment failure patterns and conversational risks.",
    misses: "Validated downstream psychiatric outcomes.",
    opportunity: "Co-develop clinical-facing safety benchmarks.",
    href: "https://www.anthropic.com/",
    tags: [DOC_TAGS.aiLabs, DOC_TAGS.safety, DOC_TAGS.mechanisms],
  },
  google_deepmind: {
    id: "google_deepmind",
    name: "Google DeepMind",
    type: "company",
    layer: "ai-labs-alignment",
    role: "Frontier model research and safety organization",
    leverage: "Broad technical research capacity and evaluation infrastructure.",
    sees: "Scaling behavior and model capability-risk tradeoffs.",
    misses: "Care-pathway linkage to psychiatric progression.",
    opportunity: "Support shared cross-lab evaluation standards tied to clinical indicators.",
    href: "https://deepmind.google/",
    tags: [DOC_TAGS.aiLabs, DOC_TAGS.research, DOC_TAGS.governance],
  },
  dario_amodei: {
    id: "dario_amodei",
    name: "Dario Amodei",
    type: "individual",
    layer: "ai-labs-alignment",
    organization: "Anthropic",
    role: "AI safety and scaling leader",
    leverage: "Can steer high-level safety priorities and disclosure posture.",
    sees: "Systemic model risk discussions and strategic safeguards.",
    misses: "Patient-level verified outcomes.",
    opportunity: "Advance joint safety reporting with clinical partners.",
    tags: [DOC_TAGS.aiLabs, DOC_TAGS.governance, DOC_TAGS.positioning],
  },
  jan_leike: {
    id: "jan_leike",
    name: "Jan Leike",
    type: "individual",
    layer: "ai-labs-alignment",
    role: "Alignment and superalignment researcher",
    leverage: "Mechanism-level framing of alignment and failure modes.",
    sees: "Reward misspecification and agreement-seeking dynamics.",
    misses: "Clinical-level labeling for severe real-world cases.",
    opportunity: "Translate alignment concepts into clinical risk language.",
    tags: [DOC_TAGS.mechanisms, DOC_TAGS.sycophancy, DOC_TAGS.framework],
  },
  geoffrey_hinton: {
    id: "geoffrey_hinton",
    name: "Geoffrey Hinton",
    type: "individual",
    layer: "ai-labs-alignment",
    role: "AI pioneer and safety risk voice",
    leverage: "High public credibility to elevate systemic AI risk discourse.",
    sees: "Macro-level AI risk trajectories.",
    misses: "Operational care-level evidence and intervention pathways.",
    opportunity: "Increase policy urgency for clinically grounded safeguards.",
    tags: [DOC_TAGS.positioning, DOC_TAGS.policy, DOC_TAGS.aiLabs],
  },

  stanford_io: {
    id: "stanford_io",
    name: "Stanford Internet Observatory",
    type: "institution",
    layer: "trust-safety-platform-risk",
    role: "Platform harm and digital risk observatory",
    leverage: "Incident pattern analysis and internet-scale harm framing.",
    sees: "Escalation loops and behavioral drift signals.",
    misses: "Clinical diagnosis progression and treatment outcomes.",
    opportunity: "Define incident schemas that can bridge into care systems.",
    href: "https://cyber.fsi.stanford.edu/io",
    tags: [DOC_TAGS.trustAndSafety, DOC_TAGS.chatLogEvidence, DOC_TAGS.gapAnalysis],
  },
  ccdh: {
    id: "ccdh",
    name: "Center for Countering Digital Hate",
    type: "institution",
    layer: "trust-safety-platform-risk",
    leverage: "Public risk reporting and platform accountability pressure.",
    sees: "Harmful interaction trends and amplification patterns.",
    misses: "Longitudinal psychiatric outcomes.",
    opportunity: "Support cross-platform incident taxonomies with clinical handoff potential.",
    href: "https://counterhate.com/",
    tags: [DOC_TAGS.trustAndSafety, DOC_TAGS.advocacy, DOC_TAGS.risk],
  },
  partnership_on_ai: {
    id: "partnership_on_ai",
    name: "Partnership on AI",
    type: "institution",
    layer: "trust-safety-platform-risk",
    leverage: "Cross-sector convening power for responsible AI standards.",
    sees: "Governance and implementation challenges across stakeholders.",
    misses: "Clinical endpoint validation pipelines.",
    opportunity: "Coordinate interoperability standards and shared reporting templates.",
    href: "https://partnershiponai.org/",
    tags: [DOC_TAGS.governance, DOC_TAGS.trustAndSafety, DOC_TAGS.execution],
  },

  who: {
    id: "who",
    name: "World Health Organization",
    type: "institution",
    layer: "policy-standards",
    leverage: "Global public-health norm setting and guidance authority.",
    sees: "Population-level risk and implementation disparities.",
    misses: "Fine-grained LLM-specific clinical evidence standards.",
    opportunity: "Codify terminology and baseline reporting guidance.",
    href: "https://www.who.int/",
    tags: [DOC_TAGS.policy, DOC_TAGS.publicHealth, DOC_TAGS.governance],
  },
  apa: {
    id: "apa",
    name: "American Psychiatric Association",
    type: "institution",
    layer: "policy-standards",
    leverage: "Clinical guideline influence and DSM stewardship.",
    sees: "Clinical practice needs and specialty consensus pathways.",
    misses: "Robust evidence packages specific to AI-mediated psychosis pathways.",
    opportunity: "Host formal terminology and guideline working groups.",
    href: "https://www.psychiatry.org/",
    tags: [DOC_TAGS.policy, DOC_TAGS.clinical, DOC_TAGS.governance],
  },
  nice: {
    id: "nice",
    name: "NICE",
    type: "institution",
    layer: "policy-standards",
    organization: "National Institute for Health and Care Excellence",
    leverage: "Evidence-based care guidance with implementation impact.",
    sees: "Intervention evidence quality and service delivery implications.",
    misses: "Mature comparative datasets on AI-linked psychosis interventions.",
    opportunity: "Define evidence thresholds for guidance inclusion.",
    href: "https://www.nice.org.uk/",
    tags: [DOC_TAGS.policy, DOC_TAGS.evidence, DOC_TAGS.execution],
  },

  rosalind_picard: {
    id: "rosalind_picard",
    name: "Rosalind Picard",
    type: "individual",
    layer: "adjacent-bridge",
    organization: "MIT",
    role: "Affective computing and digital mental health researcher",
    leverage: "Bridges sensing, behavior signals, and mental health intervention design.",
    sees: "Digital biomarkers and emotional state proxies.",
    misses: "Shared psychosis-specific AI interaction taxonomy.",
    opportunity: "Build bridge metrics for translational studies.",
    tags: [DOC_TAGS.research, DOC_TAGS.metrics, DOC_TAGS.positioning],
  },
  andrew_beam: {
    id: "andrew_beam",
    name: "Andrew Beam",
    type: "individual",
    layer: "adjacent-bridge",
    organization: "Harvard",
    role: "AI and health data science researcher",
    leverage: "Translational methods connecting machine learning and clinical evidence.",
    sees: "Data integration challenges in healthcare AI.",
    misses: "Dedicated datasets linking LLM behavior to psychosis outcomes.",
    opportunity: "Design interoperable study protocols for outcome linkage.",
    tags: [DOC_TAGS.research, DOC_TAGS.evidence, DOC_TAGS.execution],
  },
  ai_now: {
    id: "ai_now",
    name: "AI Now Institute",
    type: "institution",
    layer: "adjacent-bridge",
    leverage: "Policy-forward AI accountability analysis.",
    sees: "Social impact and power asymmetries in AI deployment.",
    misses: "Clinical granularity for psychosis progression pathways.",
    opportunity: "Translate clinical risk findings into governance pressure.",
    href: "https://ainowinstitute.org/",
    tags: [DOC_TAGS.policy, DOC_TAGS.advocacy, DOC_TAGS.governance],
  },
  rumman_chowdhury: {
    id: "rumman_chowdhury",
    name: "Rumman Chowdhury",
    type: "individual",
    layer: "adjacent-bridge",
    role: "AI accountability and governance leader",
    leverage: "Connects technical risk narratives to policy and civil-society action.",
    sees: "Operational harms and governance failure modes.",
    misses: "Clinical longitudinal outcome evidence.",
    opportunity: "Accelerate cross-sector coalition building around safeguards.",
    tags: [DOC_TAGS.governance, DOC_TAGS.advocacy, DOC_TAGS.positioning],
  },

  psychiatric_hospitals: {
    id: "psychiatric_hospitals",
    name: "Psychiatric hospitals",
    type: "care-operator",
    layer: "care-delivery",
    leverage: "First high-acuity intake point where severe AI-linked episodes present.",
    sees: "Acute crisis narratives, admission context, and stabilization needs.",
    misses: "Standardized upstream AI interaction histories.",
    opportunity: "Add structured AI exposure capture in intake workflows.",
    tags: [DOC_TAGS.medical, DOC_TAGS.earlySignals, DOC_TAGS.execution],
  },
  crisis_hotlines: {
    id: "crisis_hotlines",
    name: "Crisis hotlines",
    type: "care-operator",
    layer: "care-delivery",
    leverage: "Early interception before hospitalization.",
    sees: "Real-time distress narratives and escalation dynamics.",
    misses: "Post-call longitudinal outcomes and standardized AI-risk labeling.",
    opportunity: "Create triage prompts for AI-mediated belief reinforcement.",
    tags: [DOC_TAGS.medical, DOC_TAGS.emergency, DOC_TAGS.earlySignals],
  },
  residential_treatment_centers: {
    id: "residential_treatment_centers",
    name: "Residential treatment centers",
    type: "care-operator",
    layer: "care-delivery",
    leverage: "Observe sustained recovery trajectories and relapse patterns.",
    sees: "Longer-term behavioral and treatment response arcs.",
    misses: "Integrated platform telemetry and pre-admission conversation traces.",
    opportunity: "Pilot longitudinal AI exposure and relapse monitoring protocols.",
    tags: [DOC_TAGS.medical, DOC_TAGS.clinicalEvidence, DOC_TAGS.multiTurnRisk],
  },
};

export const AI_PSYCHOSIS_ACTOR_GROUPS = {
  clinicalPrograms: ["epinet", "nimh", "ontrackny", "orygen"] as const,
  clinicalFigures: ["john_torous", "patricia_arean", "philip_mcguire"] as const,
  aiLabs: ["openai", "anthropic", "google_deepmind"] as const,
  aiFigures: ["dario_amodei", "jan_leike", "geoffrey_hinton"] as const,
  trustSafety: ["stanford_io", "ccdh", "partnership_on_ai"] as const,
  policyStandards: ["who", "apa", "nice"] as const,
  bridgeLayer: ["rosalind_picard", "andrew_beam", "ai_now", "rumman_chowdhury"] as const,
  careDelivery: ["psychiatric_hospitals", "crisis_hotlines", "residential_treatment_centers"] as const,
};
