import { DOC_TAGS } from "@/lib/records/tag-records";

export const REFERENCES = {
  ai_psychosis_jmir_2025: {
    id: "ai_psychosis_jmir_2025",
    authors: "Hudon, A. & Stip, E.",
    year: "2025",
    title: "Delusional Experiences Emerging From AI Chatbot Interactions or \"AI Psychosis\"",
    source: "JMIR Mental Health (Viewpoint)",
    note: "Frames AI psychosis via stress-vulnerability, theory of mind, and digital therapeutic alliance; advances translational safeguards and research domains.",
    tags: [DOC_TAGS.aiPsychosisFramework, DOC_TAGS.literatureCase],
    photo: {
      src: "/references/jmir-delusions.jpg",
      alt: "Delusional Experiences Emerging From AI Chatbot Interactions or AI Psychosis",
    },
    href: "https://mental.jmir.org/2025/1/e85799/",
    correspondingAuthor: "Alexandre Hudon",
    correspondingAuthorEmail: "alexandre.hudon.1@umontreal.ca",
    doi: "10.2196/85799",
    pmid: "41273266",
    affiliations: [
      "Department of Psychiatry and Addictology, Faculty of Medicine, Universite de Montreal, Montreal, QC, Canada",
      "Unite de recherche en psychiatrie, Departement de psychiatrie, Institut universitaire en sante mentale de Montreal, Montreal, QC, Canada",
      "Centre de recherche, Institut universitaire en sante mentale de Montreal, Montreal, QC, Canada",
      "Department of Psychiatry, Institut national de psychiatrie legale Philippe-Pinel, Montreal, QC, Canada",
      "Centre de recherche en pedagogie de la sante, Universite de Montreal, Montreal, QC, Canada",
      "Department of Psychiatry, United Arab Emirates University, Al-Ain, United Arab Emirates",
    ],
  },
  ai_associated_delusions_lancet_2026: {
    id: "ai_associated_delusions_lancet_2026",
    authors: "Morrin, H., Nicholls, L., Levin, M., Yiend, J., Iyengar, U., DelGuidice, F., et al.",
    year: "2026",
    title: "Artificial intelligence-associated delusions and large language models: risks, mechanisms of delusion co-creation, and safeguarding strategies",
    source: "The Lancet Psychiatry (Personal View, online ahead of print)",
    note: "Examines risks of delusion co-creation in vulnerable users and proposes AI-informed care protocols for epistemic security.",
    tags: [DOC_TAGS.aiDelusionSafeguards, DOC_TAGS.literatureCase],
    photo: {
      src: "/references/lancet-delusions.jpg",
      alt: "Artificial intelligence-associated delusions and large language models",
    },
    href: "https://www.thelancet.com/journals/lanpsy/article/PIIS2215-0366(25)00396-7/abstract",
    correspondingAuthor: "Hamilton Morrin",
    correspondingAuthorEmail: "hamilton.morrin@kcl.ac.uk",
    doi: "10.1016/S2215-0366(25)00396-7",
    pmid: "41796598",
    affiliations: [
      "Department of Psychosis Studies, Institute of Psychiatry, Psychology and Neuroscience, King's College London, London, UK; South London and the Maudsley NHS Foundation Trust, London, UK",
      "The Graduate Center, City University of New York, New York, NY, USA",
      "Allen Discovery Center, Tufts University, Medford, MA, USA",
      "Department of Psychosis Studies, Institute of Psychiatry, Psychology and Neuroscience, King's College London, London, UK",
      "Lived Experience Advisory Board, Department of Psychosis Studies, Institute of Psychiatry, Psychology and Neuroscience, King's College London, London, UK",
      "Department of Psychology, Durham University, Durham, UK",
    ],
  },
} as const;
