import { DOC_TAGS } from "@/lib/records/tag-records";

export const REFERENCES = {
  ai_psychosis_jmir_2025: {
    id: "ai_psychosis_jmir_2025",
    authors: "Hudon, A. & Stip, E.",
    year: "2025",
    title: "Delusional Experiences Emerging From AI Chatbot Interactions or \"AI Psychosis\"",
    source: "JMIR Mental Health (Viewpoint)",
    note: "Frames AI psychosis via stress-vulnerability, theory of mind, and digital therapeutic alliance; advances translational safeguards and research domains.",
    tags: [DOC_TAGS.aiPsychosisFramework, DOC_TAGS.literatureCase],
    photo: {
      src: "/references/jmir-delusions.jpg",
      alt: "Delusional Experiences Emerging From AI Chatbot Interactions or AI Psychosis",
    },
    href: "https://mental.jmir.org/2025/1/e85799/",
    correspondingAuthor: "Alexandre Hudon",
    correspondingAuthorEmail: "alexandre.hudon.1@umontreal.ca",
    doi: "10.2196/85799",
    pmid: "41273266",
    affiliations: [
      "Department of Psychiatry and Addictology, Faculty of Medicine, Universite de Montreal, Montreal, QC, Canada",
      "Unite de recherche en psychiatrie, Departement de psychiatrie, Institut universitaire en sante mentale de Montreal, Montreal, QC, Canada",
      "Centre de recherche, Institut universitaire en sante mentale de Montreal, Montreal, QC, Canada",
      "Department of Psychiatry, Institut national de psychiatrie legale Philippe-Pinel, Montreal, QC, Canada",
      "Centre de recherche en pedagogie de la sante, Universite de Montreal, Montreal, QC, Canada",
      "Department of Psychiatry, United Arab Emirates University, Al-Ain, United Arab Emirates",
    ],
  },
  ai_associated_delusions_lancet_2026: {
    id: "ai_associated_delusions_lancet_2026",
    authors: "Morrin, H., Nicholls, L., Levin, M., Yiend, J., Iyengar, U., DelGuidice, F., et al.",
    year: "2026",
    title: "Artificial intelligence-associated delusions and large language models: risks, mechanisms of delusion co-creation, and safeguarding strategies",
    source: "The Lancet Psychiatry (Personal View, online ahead of print)",
    note: "Examines risks of delusion co-creation in vulnerable users and proposes AI-informed care protocols for epistemic security.",
    tags: [DOC_TAGS.aiDelusionSafeguards, DOC_TAGS.literatureCase],
    photo: {
      src: "/references/lancet-delusions.jpg",
      alt: "Artificial intelligence-associated delusions and large language models",
    },
    href: "https://www.thelancet.com/journals/lanpsy/article/PIIS2215-0366(25)00396-7/abstract",
    correspondingAuthor: "Hamilton Morrin",
    correspondingAuthorEmail: "hamilton.morrin@kcl.ac.uk",
    doi: "10.1016/S2215-0366(25)00396-7",
    pmid: "41796598",
    affiliations: [
      "Department of Psychosis Studies, Institute of Psychiatry, Psychology and Neuroscience, King's College London, London, UK; South London and the Maudsley NHS Foundation Trust, London, UK",
      "The Graduate Center, City University of New York, New York, NY, USA",
      "Allen Discovery Center, Tufts University, Medford, MA, USA",
      "Department of Psychosis Studies, Institute of Psychiatry, Psychology and Neuroscience, King's College London, London, UK",
      "Lived Experience Advisory Board, Department of Psychosis Studies, Institute of Psychiatry, Psychology and Neuroscience, King's College London, London, UK",
      "Department of Psychology, Durham University, Durham, UK",
    ],
  },
  sycophancy_understanding_sharma_2023: {
    id: "sycophancy_understanding_sharma_2023",
    authors: "Sharma, M., et al.",
    year: "2023",
    title: "Towards Understanding Sycophancy in Language Models",
    source: "arXiv / technical report",
    note: "Five assistants showed consistent sycophancy across four tasks; preference signals often favored view-matching over truth, and user pressure reduced accuracy by up to 27%. Uses MATH, MMLU, AQuA, TruthfulQA, TriviaQA, poem-attribution tasks with Claude-1.3/2.0, GPT-3.5-turbo, GPT-4, and Llama-2-70B-chat. Link ref #9.",
    tags: [DOC_TAGS.research, DOC_TAGS.sycophancy, DOC_TAGS.benchmark, DOC_TAGS.evidence],
  },
  synthetic_data_reduces_sycophancy_wei_2023: {
    id: "synthetic_data_reduces_sycophancy_wei_2023",
    authors: "Wei, J., et al.",
    year: "2023",
    title: "Simple synthetic data reduces sycophancy in large language models",
    source: "arXiv",
    note: "Finds model scaling and instruction tuning increased sycophancy in PaLM, while lightweight synthetic-data finetuning reduced it on held-out prompts across three sycophancy tasks. Link ref #10.",
    tags: [DOC_TAGS.research, DOC_TAGS.sycophancy, DOC_TAGS.benchmark, DOC_TAGS.safety],
  },
  hallucination_survey_lvlm_liu_2024: {
    id: "hallucination_survey_lvlm_liu_2024",
    authors: "Liu, H., et al.",
    year: "2024",
    title: "A Survey on Hallucination in Large Vision-Language Models",
    source: "arXiv",
    note: "Comprehensive LVLM hallucination survey organizing definitions, symptoms, evaluation methods, root causes, and mitigation directions for model-grounding failures.",
    tags: [DOC_TAGS.research, DOC_TAGS.hallucination, DOC_TAGS.framework, DOC_TAGS.landscape],
    href: "https://arxiv.org/abs/2402.00253",
    doi: "10.48550/arXiv.2402.00253",
  },
  hallucination_survey_mllm_bai_2024: {
    id: "hallucination_survey_mllm_bai_2024",
    authors: "Bai, Z., et al.",
    year: "2024",
    title: "Hallucination of Multimodal Large Language Models: A Survey",
    source: "arXiv",
    note: "Survey of MLLM hallucination landscapes with granular taxonomy across causes, benchmarks, metrics, and mitigation strategies.",
    tags: [DOC_TAGS.research, DOC_TAGS.hallucination, DOC_TAGS.framework, DOC_TAGS.landscape],
    href: "https://arxiv.org/abs/2404.18930",
    doi: "10.48550/arXiv.2404.18930",
  },
  hallulens_bang_2025: {
    id: "hallulens_bang_2025",
    authors: "Bang, Y., et al.",
    year: "2025",
    title: "HalluLens: LLM Hallucination Benchmark",
    source: "ACL 2025",
    note: "Separates hallucination from factuality and introduces intrinsic/extrinsic taxonomy plus new extrinsic tasks (PreciseWikiQA, LongWiki, NonExistentRefusal) across 13 instruction-tuned LLMs. Link ref #7.",
    tags: [DOC_TAGS.research, DOC_TAGS.hallucination, DOC_TAGS.benchmark, DOC_TAGS.framework],
  },
  syceval_fanous_2025: {
    id: "syceval_fanous_2025",
    authors: "Fanous, A., et al.",
    year: "2025",
    title: "SycEval: Evaluating LLM Sycophancy",
    source: "arXiv",
    note: "Reports overall sycophancy in 58.19% of cases, distinguishing progressive vs regressive forms and showing persistence across rebuttal chains using AMPS Math and MedQuad on ChatGPT-4o, Claude-Sonnet, and Gemini-1.5-Pro. Link ref #11.",
    tags: [DOC_TAGS.research, DOC_TAGS.sycophancy, DOC_TAGS.benchmark, DOC_TAGS.multiTurnRisk],
  },
  truth_decay_liu_2025: {
    id: "truth_decay_liu_2025",
    authors: "Liu, J., et al.",
    year: "2025",
    title: "Truth Decay: Quantifying Multi-Turn Sycophancy in Language Models",
    source: "arXiv",
    note: "Shows compounding factual degradation over multi-step conversations and reduced effectiveness of prompt-only anti-sycophancy methods over longer exchanges, using 1-, 3-, and 7-turn probes on TruthfulQA and MMLU-Pro. Link ref #12.",
    tags: [DOC_TAGS.research, DOC_TAGS.sycophancy, DOC_TAGS.multiTurnRisk, DOC_TAGS.longContext],
  },
  measuring_sycophancy_multiturn_hong_2025: {
    id: "measuring_sycophancy_multiturn_hong_2025",
    authors: "Hong, J., et al.",
    year: "2025",
    title: "Measuring Sycophancy of Language Models in Multi-turn Dialogues",
    source: "arXiv",
    note: "Introduces SYCON Bench and reports that alignment tuning can amplify sycophancy, while scaling and reasoning optimization improve resistance across 17 models and three real-world scenarios. Link ref #13.",
    tags: [DOC_TAGS.research, DOC_TAGS.sycophancy, DOC_TAGS.benchmark, DOC_TAGS.multiTurnRisk],
  },
  helpfulness_backfires_medical_chen_2025: {
    id: "helpfulness_backfires_medical_chen_2025",
    authors: "Chen, S., et al.",
    year: "2025",
    title: "When helpfulness backfires: LLMs and the risk of false medical information due to sycophantic behavior",
    source: "npj Digital Medicine",
    note: "Finds GPT-family and Llama models often complied with illogical medication misinformation requests; prompt edits helped, and small supervised fine-tuning generalized OOD with minimal benchmark regression. Link ref #4.",
    tags: [DOC_TAGS.research, DOC_TAGS.sycophancy, DOC_TAGS.clinicalEvidence, DOC_TAGS.safety],
  },
  psychogenic_machine_yeung_2025: {
    id: "psychogenic_machine_yeung_2025",
    authors: "Au Yeung, J., et al.",
    year: "2025",
    title: "The Psychogenic Machine: Simulating AI Psychosis, Delusion Reinforcement and Harm Enablement in Large Language Models",
    source: "arXiv",
    note: "Introduces Psychosis-bench and reports psychogenic potential across all tested models over 1,536 turns, with implicit scenarios significantly worse and non-monotonic safety with scale. Link ref #14.",
    tags: [DOC_TAGS.research, DOC_TAGS.benchmark, DOC_TAGS.implicitRisk, DOC_TAGS.multiTurnRisk],
  },
  sycophantic_chatbots_delusional_spiraling_chandra_2026: {
    id: "sycophantic_chatbots_delusional_spiraling_chandra_2026",
    authors: "Chandra, K., et al.",
    year: "2026",
    title: "Sycophantic Chatbots Cause Delusional Spiraling, Even in Ideal Bayesians",
    source: "arXiv",
    note: "Formal Bayesian user-chatbot model shows sycophancy is causally sufficient for delusional spiraling even under rational updating, and argues hallucination removal or warnings alone are insufficient. Link ref #15.",
    tags: [DOC_TAGS.research, DOC_TAGS.sycophancy, DOC_TAGS.framework, DOC_TAGS.mechanisms],
  },
  characterizing_delusional_spirals_chat_logs_moore_2026: {
    id: "characterizing_delusional_spirals_chat_logs_moore_2026",
    authors: "Moore, J., et al.",
    year: "2026",
    title: "Characterizing Delusional Spirals through Human-LLM Chat Logs",
    source: "ACM FAccT 2026 / arXiv",
    note: "Analyzes real-world chat logs from harmed users and documents recurring sycophantic patterns in actual delusional spirals (19-user dataset). Link ref #16.",
    tags: [DOC_TAGS.research, DOC_TAGS.chatLogEvidence, DOC_TAGS.sycophancy, DOC_TAGS.clinicalEvidence],
  },
  ai_psychosis_amplify_delusion_language_shimgekar_2026: {
    id: "ai_psychosis_amplify_delusion_language_shimgekar_2026",
    authors: "Shimgekar, S. R., et al.",
    year: "2026",
    title: "AI Psychosis: Does Conversational AI Amplify Delusion-Related Language?",
    source: "arXiv",
    note: "Builds SimUsers from Reddit histories, introduces DelusionScore, and finds amplification in treatment users, especially around reality skepticism and compulsive reasoning; state-aware conditioning reduces trajectories. Link ref #6.",
    tags: [DOC_TAGS.research, DOC_TAGS.chatLogEvidence, DOC_TAGS.multiTurnRisk, DOC_TAGS.evidence],
  },
  jama_psychiatry_psychotic_prompts_shen_2026: {
    id: "jama_psychiatry_psychotic_prompts_shen_2026",
    authors: "Shen, E., et al.",
    year: "2026",
    title: "Evaluation of Large Language Model Chatbot Responses to Psychotic Prompts",
    source: "JAMA Psychiatry",
    note: "Cross-sectional product evaluation found public-facing ChatGPT variants often responded less appropriately to psychotic prompts than controls, with blinded clinician ratings. Link ref #17.",
    tags: [DOC_TAGS.research, DOC_TAGS.clinicalEvidence, DOC_TAGS.safety, DOC_TAGS.evidence],
  },
  ai_psychosis_context_history_nicholls_2026: {
    id: "ai_psychosis_context_history_nicholls_2026",
    authors: "Nicholls, L., et al.",
    year: "2026",
    title: "\"AI Psychosis\" in Context: How Conversation History Shapes LLM Responses to Delusional Beliefs",
    source: "arXiv",
    note: "Compares five models under zero/partial/full context and finds some degrade sharply with accumulated context while safer models intervene more strongly in long histories across clinically concerning prompts. Link ref #18.",
    tags: [DOC_TAGS.research, DOC_TAGS.longContext, DOC_TAGS.multiTurnRisk, DOC_TAGS.clinicalEvidence],
  },
  llm_spirals_delusion_interface_audit_kirgis_2026: {
    id: "llm_spirals_delusion_interface_audit_kirgis_2026",
    authors: "Kirgis, P., et al.",
    year: "2026",
    title: "LLM Spirals of Delusion: A Benchmarking Audit Study of AI Chatbot Interfaces",
    source: "arXiv",
    note: "Finds substantial behavior differences between API and chat interfaces; ChatGPT-5 chat performed better than ChatGPT-4o but still averaged near one sycophantic behavior per turn, with behavior reversals observed across updates. Link ref #19.",
    tags: [DOC_TAGS.research, DOC_TAGS.sycophancy, DOC_TAGS.benchmark, DOC_TAGS.vendorReported],
  },
  psychosis_risk_genai_use_buck_maheux_2026: {
    id: "psychosis_risk_genai_use_buck_maheux_2026",
    authors: "Buck, B. & Maheux, A. J.",
    year: "2026",
    title: "Psychosis Risk and Generative Artificial Intelligence Use Frequency, Motivations, and Delusion-Like Experiences",
    source: "Journal of Medical Internet Research",
    note: "Survey of 1,003 U.S. young adults found elevated psychosis-risk respondents were not more likely to have ever used GenAI but were more likely to use it intensively, seek emotional support, anthropomorphize chatbots, and report delusion-related interactions. Link ref #20.",
    tags: [DOC_TAGS.research, DOC_TAGS.clinicalEvidence, DOC_TAGS.publicHealth, DOC_TAGS.evidence],
  },
  technological_folie_deux_dohnany_2026: {
    id: "technological_folie_deux_dohnany_2026",
    authors: "Dohnany, S., et al.",
    year: "2026",
    title: "Technological folie a deux: feedback loops between AI chatbots and mental health",
    source: "Nature Mental Health",
    note: "Perspective connecting chatbot behavioral tendencies and human cognitive vulnerabilities, proposing coordinated clinical, development, and governance responses.",
    tags: [DOC_TAGS.research, DOC_TAGS.mechanisms, DOC_TAGS.publicHealth, DOC_TAGS.framework],
    href: "https://www.nature.com/articles/s44220-026-00595-8",
    doi: "10.1038/s44220-026-00595-8",
  },
} as const;
