export type DocTag = {
  id: string;
  label: string;
  icon: string;
  description: string;
  color: string;
};

export const DOC_TAGS = {
  risk: {
    id: "risk",
    label: "Risk",
    icon: "mdi:alert-outline",
    description: "Potential harm indicators and destabilization signals.",
    color: "#dc2626",
  },
  clinicalContext: {
    id: "clinical-context",
    label: "Clinical context",
    icon: "mdi:stethoscope",
    description: "Clinical framing and psychiatric interpretation context.",
    color: "#0ea5e9",
  },
  referenced: {
    id: "referenced",
    label: "Referenced",
    icon: "mdi:book-open-variant",
    description: "Sections anchored to published sources.",
    color: "#7c3aed",
  },
  aiPsychosisFramework: {
    id: "ai-psychosis-framework",
    label: "AI psychosis framework",
    icon: "mdi:head-cog-outline",
    description: "Framework-level model for AI-associated psychosis pathways.",
    color: "#8b5cf6",
  },
  aiDelusionSafeguards: {
    id: "ai-delusion-safeguards",
    label: "AI delusion safeguards",
    icon: "mdi:shield-check-outline",
    description: "Safeguards and containment strategies for delusion co-creation risk.",
    color: "#0d9488",
  },
  literatureCase: {
    id: "literature-case",
    label: "Literature case",
    icon: "mdi:file-document-outline",
    description: "Published case framing from peer-reviewed literature.",
    color: "#4f46e5",
  },
  detection: {
    id: "detection",
    label: "Detection",
    icon: "mdi:magnify",
    description: "Signals and methods for early identification.",
    color: "#0284c7",
  },
  safety: {
    id: "safety",
    label: "Safety",
    icon: "mdi:shield-outline",
    description: "Safety mitigations and protective response practices.",
    color: "#16a34a",
  },
  earlyStage: {
    id: "early-stage",
    label: "Early stage",
    icon: "mdi:sprout-outline",
    description: "Initial phase patterns and precursor dynamics.",
    color: "#65a30d",
  },
  escalation: {
    id: "escalation",
    label: "Escalation",
    icon: "mdi:trending-up",
    description: "Progressive intensification of risk and symptoms.",
    color: "#ea580c",
  },
  criticalRisk: {
    id: "critical-risk",
    label: "Critical risk",
    icon: "mdi:alert-decagram-outline",
    description: "High-risk phase requiring urgent intervention.",
    color: "#dc2626",
  },
  emergency: {
    id: "emergency",
    label: "Emergency",
    icon: "mdi:ambulance",
    description: "Immediate-response situations with acute safety concern.",
    color: "#b91c1c",
  },
  policy: {
    id: "policy",
    label: "Policy",
    icon: "mdi:scale-balance",
    description: "Regulatory, institutional, and standards-level considerations.",
    color: "#0f766e",
  },
  advocacy: {
    id: "advocacy",
    label: "Advocacy",
    icon: "mdi:bullhorn-outline",
    description: "Stakeholder mobilization and recognition efforts.",
    color: "#c2410c",
  },
  evidence: {
    id: "evidence",
    label: "Evidence",
    icon: "mdi:clipboard-text-search-outline",
    description: "Data quality, rigor, and substantiation requirements.",
    color: "#1d4ed8",
  },
  governance: {
    id: "governance",
    label: "Governance",
    icon: "mdi:domain",
    description: "Institutional oversight, accountability, and protocols.",
    color: "#334155",
  },
  medical: {
    id: "medical",
    label: "Medical",
    icon: "mdi:medical-bag",
    description: "Clinical care delivery and treatment system roles.",
    color: "#0369a1",
  },
  publicHealth: {
    id: "public-health",
    label: "Public health",
    icon: "mdi:earth",
    description: "Population-level health priorities and intervention planning.",
    color: "#059669",
  },
  research: {
    id: "research",
    label: "Research",
    icon: "mdi:flask-outline",
    description: "Empirical investigation, validation, and discovery.",
    color: "#7c3aed",
  },
  positioning: {
    id: "positioning",
    label: "Positioning",
    icon: "mdi:compass-outline",
    description: "Strategic framing of scope, leverage, and direction.",
    color: "#7c2d12",
  },
  framework: {
    id: "framework",
    label: "Framework",
    icon: "mdi:vector-polyline",
    description: "Structured conceptual model for classification and action.",
    color: "#4338ca",
  },
  metrics: {
    id: "metrics",
    label: "Metrics",
    icon: "mdi:chart-line",
    description: "Operational indicators for measurement and monitoring.",
    color: "#2563eb",
  },
  execution: {
    id: "execution",
    label: "Execution",
    icon: "mdi:rocket-launch-outline",
    description: "Implementation plan and operational rollout steps.",
    color: "#0891b2",
  },
  fieldStatus: {
    id: "field-status",
    label: "Field status",
    icon: "mdi:radar",
    description: "Current maturity level and ecosystem readiness.",
    color: "#6d28d9",
  },
  landscape: {
    id: "landscape",
    label: "Landscape",
    icon: "mdi:map-outline",
    description: "Stakeholder map and ecosystem composition.",
    color: "#1d4ed8",
  },
  clinical: {
    id: "clinical",
    label: "Clinical",
    icon: "mdi:hospital-box-outline",
    description: "Clinical actor roles and care pathway relevance.",
    color: "#0284c7",
  },
  aiLabs: {
    id: "ai-labs",
    label: "AI labs",
    icon: "mdi:robot-outline",
    description: "Model builders and safety research organizations.",
    color: "#4f46e5",
  },
  mechanisms: {
    id: "mechanisms",
    label: "Mechanisms",
    icon: "mdi:cogs",
    description: "Underlying causal and reinforcement processes.",
    color: "#7c3aed",
  },
  trustAndSafety: {
    id: "trust-and-safety",
    label: "Trust and safety",
    icon: "mdi:shield-account-outline",
    description: "Platform risk teams and real-time incident controls.",
    color: "#0f766e",
  },
  earlySignals: {
    id: "early-signals",
    label: "Early signals",
    icon: "mdi:signal-distance-variant",
    description: "Weak signals and emerging risk indicators.",
    color: "#ca8a04",
  },
  gapAnalysis: {
    id: "gap-analysis",
    label: "Gap analysis",
    icon: "mdi:chart-timeline-variant",
    description: "Cross-silo capability gaps and missing interfaces.",
    color: "#475569",
  },
} as const satisfies Record<string, DocTag>;

